name: dart_address
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  tuple: ^2.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  melos: ^6.1.0
  test: ^1.24.0
