name: ohochat_address
version: 0.0.1+rc3

description: |
  A lightweight and efficient Thailand address helper for Flutter, 
  designed to simplify address handling for Thai locations. With this package, 
  you can quickly build address-based features without dealing with complex data relationships. 
  It supports mobile, web, and desktop platforms, making it a versatile choice for any Flutter project.

topics:
  - address
  - thailand
  - ohochat
  - location
  - input

homepage: https://github.com/ohoexperience/dart_address/tree/main/packages/address
repository: https://github.com/ohoexperience/dart_address/tree/main/packages/address

environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  resource_importer: ^0.2.0

resource_importer:
  resources:
    rawDB: 
      path: 'assets/minify_db.json'
      type: String