name: ohochat_address
description: "A no-nonsense Thailand address helper."
version: 0.0.1+rc

repository: https://github.com/ohoexperience/dart_address/tree/main/packages/address
environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  resource_importer: ^0.2.0

resource_importer:
  resources:
    rawDB: 
      path: 'assets/minify_db.json'
      type: String