name: ohochat_address
description: "A no-nonsense Thailand address helper."
version: 0.0.1

repository: https://github.com/ohoexperience/dart_address/tree/main/packages/address
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  resource_importer: ^0.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
      - assets/minify_db.json

resource_importer:
  resources:
    rawDB: 
      path: 'assets/minify_db.json'
      type: String