name: ohochat_address
version: 1.0.0

description: |
  A lightweight Thailand address helper for Flutter, 
  simplifying address handling across mobile, web, and desktop platforms.

topics:
  - address
  - thailand
  - ohochat
  - location
  - input

homepage: https://github.com/ohoexperience/dart_address/tree/main/packages/ohochat_address
repository: https://github.com/ohoexperience/dart_address/tree/main/packages/ohochat_address

environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  resource_importer: ^0.2.0

resource_importer:
  resources:
    rawDB: 
      path: 'assets/minify_db.json'
      type: String