name: address_dart
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
